services:
  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: taskmanager
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./Java/taskmanager
    container_name: backend_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/taskmanager
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: always

  frontend:
    build:
      context: ./Front/taskmanager
    container_name: react_app
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

volumes:
  db_data:
